server:
  port: 8080
  
spring:
  application:
    name: Gateway
    
zuul:
  prefix: /api
  routes:
    first:
      path: /first/**
      service-id: EurekaClient-1

ribbon:
  eureka:
    enabled: true
    
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.109:8761/eureka/
      registerWithEureka: true